apiVersion: v1
kind: PersistentVolume
metadata:
  name: video-rag-models-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/video-rag-models
    type: DirectoryOrCreate

