apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: video-rag-models-pvc
  namespace: video-rag
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
  volumeName: video-rag-models-pv

