apiVersion: v1
kind: Secret
metadata:
  name: video-rag-env
  namespace: video-rag
type: Opaque
stringData:
  PYTHONPATH: "src"
  LOG_FILE: "logs/app.log"
  SUBTITLES_DIR: "downloads/subtitles"
  SUPABASE_URL: "<SUPABASE_URL>"
  SUPABASE_KEY: "<SUPABASE_KEY>"
  USER: "<DB_USER>"
  HOST: "<DB_HOST>"
  PORT: "<DB_PORT>"
  DBNAME: "<DB_NAME>"
  APP_PORT: "8000"
  CONFIG_PATH: "config/config.yaml"

