apiVersion: v1
kind: Service
metadata:
  name: video-rag-api-service
  namespace: video-rag
  labels:
    app: video-rag-api
spec:
  type: NodePort
  selector:
    app: video-rag-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
      protocol: TCP

