apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: video-rag-models-pvc
  namespace: video-rag
spec:
  volumeName: video-rag-models-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
