apiVersion: v1
kind: Secret
metadata:
  name: video-rag-env
  namespace: video-rag
type: Opaque
stringData:
  ENVIRONMENT: "aws"
  CONFIG_PATH: "config/config.aws.yaml"

  STORAGE_BACKEND: "s3"
  S3_BUCKET: "<YOUR_S3_BUCKET>"
  S3_PREFIX: "subtitles/"

  RDS_HOST: "<YOUR_RDS_ENDPOINT>"
  RDS_PORT: "5432"
  RDS_DATABASE: "videodb"
  RDS_USER: "postgres"
  RDS_PASSWORD: "<YOUR_RDS_PASSWORD>"
  USER: "<YOUR_RDS_USER>"
  HOST: "<YOUR_RDS_ENDPOINT>"
  PORT: "5432"
  DBNAME: "videodb"

  APP_HOST: "0.0.0.0"
  APP_PORT: "8000"
  PYTHONPATH: "src"
  LOG_FILE: "/var/log/app.log"
